apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserviceazure-deployment
  labels: #tag para deployment
    app: microserviceazure
spec:
  replicas: 1 #recomendado 2+ réplicas, porém reduzido devido a disponibilidade de pods da minha assinatura gratuita
  strategy:
    type: RollingUpdate #Estratégias de atualização
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: microserviceazure
  template:
    metadata:
      labels:
        app: microserviceazure
    spec:
      containers:
        - name: microserviceazure-container
          image: alissonlimadev.azurecr.io/microserviceazure:latest #endereço da imagem
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits: #Limite de recursos
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 500m
              memory: 300Mi
      imagePullSecrets:
        - name: regcred